services:
  postgres:
    ports:
      - "5432:5432"

  frontend:
    networks:
      - internal
    ports:
      - "8080:80"

  backend:
    ports:
      - "4000:4000"

networks:
  proxy:
    external: false
