/* eslint-disable */
import * as types from './graphql';



/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 * Learn more about it here: https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#reducing-bundle-size
 */
type Documents = {
    "\n  query CharacterInfo($name: String!, $realm: String!, $region: String!, $bypassCache: Boolean) {\n    character(name: $name, realm: $realm, region: $region, bypassCache: $bypassCache) {\n      name\n      realm\n      region\n      class\n      race\n      activeSpec\n      faction\n      gender\n      level\n      equippedItemLevel\n      averageItemLevel\n      achievementPoints\n      guild {\n        name\n        realm\n      }\n      avatarUrl\n    }\n  }\n": typeof types.CharacterInfoDocument,
    "\n  query CharacterLogs(\n    $name: String!\n    $realm: String!\n    $region: String!\n    $role: RoleType\n    $metric: Metric\n    $difficulty: Difficulty\n    $byBracket: Boolean\n    $zoneId: Int\n    $bypassCache: Boolean\n  ) {\n    character(\n      name: $name\n      realm: $realm\n      region: $region\n      role: $role\n      metric: $metric\n      difficulty: $difficulty\n      byBracket: $byBracket\n      zoneId: $zoneId\n      bypassCache: $bypassCache\n    ) {\n      warcraftLogs {\n        bestPerformanceAverage\n        medianPerformanceAverage\n        metric\n        difficulty\n\n        raidRankings {\n          spec\n          encounter {\n            id\n            name\n          }\n          rankPercent\n          medianPercent\n          bestAmount\n          totalKills\n          bestRank {\n            ilvl\n          }\n        }\n      }\n    }\n  }\n": typeof types.CharacterLogsDocument,
    "\n  query CharacterRaiderIo($name: String!, $realm: String!, $region: String!, $bypassCache: Boolean) {\n    character(name: $name, realm: $realm, region: $region, bypassCache: $bypassCache) {\n      raiderIo {\n        bestMythicPlusRuns {\n          dungeon\n          short_name\n          challange_mode_id\n          key_level\n          completed_at\n          icon_url\n          background_image_url\n          url\n          keystone_upgrades\n          role\n          spec {\n            name\n            slug\n          }\n          class {\n            name\n            slug\n          }\n        }\n        recentMythicPlusRuns {\n          dungeon\n          short_name\n          challange_mode_id\n          key_level\n          completed_at\n          icon_url\n          background_image_url\n          url\n          keystone_upgrades\n          role\n          spec {\n            name\n            slug\n          }\n          class {\n            name\n            slug\n          }\n        }\n        raidProgression {\n          raid\n          total_bosses\n          heroic_bosses_killed\n          mythic_bosses_killed\n          normal_bosses_killed\n          expansion_id\n        }\n        currentSeason {\n          all { score color }\n          dps { score color }\n          healer { score color }\n          tank { score color }\n        }\n        previousSeason {\n          all { score color }\n          dps { score color }\n          healer { score color }\n          tank { score color }\n        }\n      }\n    }\n  }\n": typeof types.CharacterRaiderIoDocument,
    "\n  query CharacterSearch($searchString: String!, $region: String!) {\n    characterSuggestions(searchString: $searchString, region: $region) {\n      name\n      realm\n      region\n    }\n  }\n": typeof types.CharacterSearchDocument,
};
const documents: Documents = {
    "\n  query CharacterInfo($name: String!, $realm: String!, $region: String!, $bypassCache: Boolean) {\n    character(name: $name, realm: $realm, region: $region, bypassCache: $bypassCache) {\n      name\n      realm\n      region\n      class\n      race\n      activeSpec\n      faction\n      gender\n      level\n      equippedItemLevel\n      averageItemLevel\n      achievementPoints\n      guild {\n        name\n        realm\n      }\n      avatarUrl\n    }\n  }\n": types.CharacterInfoDocument,
    "\n  query CharacterLogs(\n    $name: String!\n    $realm: String!\n    $region: String!\n    $role: RoleType\n    $metric: Metric\n    $difficulty: Difficulty\n    $byBracket: Boolean\n    $zoneId: Int\n    $bypassCache: Boolean\n  ) {\n    character(\n      name: $name\n      realm: $realm\n      region: $region\n      role: $role\n      metric: $metric\n      difficulty: $difficulty\n      byBracket: $byBracket\n      zoneId: $zoneId\n      bypassCache: $bypassCache\n    ) {\n      warcraftLogs {\n        bestPerformanceAverage\n        medianPerformanceAverage\n        metric\n        difficulty\n\n        raidRankings {\n          spec\n          encounter {\n            id\n            name\n          }\n          rankPercent\n          medianPercent\n          bestAmount\n          totalKills\n          bestRank {\n            ilvl\n          }\n        }\n      }\n    }\n  }\n": types.CharacterLogsDocument,
    "\n  query CharacterRaiderIo($name: String!, $realm: String!, $region: String!, $bypassCache: Boolean) {\n    character(name: $name, realm: $realm, region: $region, bypassCache: $bypassCache) {\n      raiderIo {\n        bestMythicPlusRuns {\n          dungeon\n          short_name\n          challange_mode_id\n          key_level\n          completed_at\n          icon_url\n          background_image_url\n          url\n          keystone_upgrades\n          role\n          spec {\n            name\n            slug\n          }\n          class {\n            name\n            slug\n          }\n        }\n        recentMythicPlusRuns {\n          dungeon\n          short_name\n          challange_mode_id\n          key_level\n          completed_at\n          icon_url\n          background_image_url\n          url\n          keystone_upgrades\n          role\n          spec {\n            name\n            slug\n          }\n          class {\n            name\n            slug\n          }\n        }\n        raidProgression {\n          raid\n          total_bosses\n          heroic_bosses_killed\n          mythic_bosses_killed\n          normal_bosses_killed\n          expansion_id\n        }\n        currentSeason {\n          all { score color }\n          dps { score color }\n          healer { score color }\n          tank { score color }\n        }\n        previousSeason {\n          all { score color }\n          dps { score color }\n          healer { score color }\n          tank { score color }\n        }\n      }\n    }\n  }\n": types.CharacterRaiderIoDocument,
    "\n  query CharacterSearch($searchString: String!, $region: String!) {\n    characterSuggestions(searchString: $searchString, region: $region) {\n      name\n      realm\n      region\n    }\n  }\n": types.CharacterSearchDocument,
};

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query CharacterInfo($name: String!, $realm: String!, $region: String!, $bypassCache: Boolean) {\n    character(name: $name, realm: $realm, region: $region, bypassCache: $bypassCache) {\n      name\n      realm\n      region\n      class\n      race\n      activeSpec\n      faction\n      gender\n      level\n      equippedItemLevel\n      averageItemLevel\n      achievementPoints\n      guild {\n        name\n        realm\n      }\n      avatarUrl\n    }\n  }\n"): typeof import('./graphql').CharacterInfoDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query CharacterLogs(\n    $name: String!\n    $realm: String!\n    $region: String!\n    $role: RoleType\n    $metric: Metric\n    $difficulty: Difficulty\n    $byBracket: Boolean\n    $zoneId: Int\n    $bypassCache: Boolean\n  ) {\n    character(\n      name: $name\n      realm: $realm\n      region: $region\n      role: $role\n      metric: $metric\n      difficulty: $difficulty\n      byBracket: $byBracket\n      zoneId: $zoneId\n      bypassCache: $bypassCache\n    ) {\n      warcraftLogs {\n        bestPerformanceAverage\n        medianPerformanceAverage\n        metric\n        difficulty\n\n        raidRankings {\n          spec\n          encounter {\n            id\n            name\n          }\n          rankPercent\n          medianPercent\n          bestAmount\n          totalKills\n          bestRank {\n            ilvl\n          }\n        }\n      }\n    }\n  }\n"): typeof import('./graphql').CharacterLogsDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query CharacterRaiderIo($name: String!, $realm: String!, $region: String!, $bypassCache: Boolean) {\n    character(name: $name, realm: $realm, region: $region, bypassCache: $bypassCache) {\n      raiderIo {\n        bestMythicPlusRuns {\n          dungeon\n          short_name\n          challange_mode_id\n          key_level\n          completed_at\n          icon_url\n          background_image_url\n          url\n          keystone_upgrades\n          role\n          spec {\n            name\n            slug\n          }\n          class {\n            name\n            slug\n          }\n        }\n        recentMythicPlusRuns {\n          dungeon\n          short_name\n          challange_mode_id\n          key_level\n          completed_at\n          icon_url\n          background_image_url\n          url\n          keystone_upgrades\n          role\n          spec {\n            name\n            slug\n          }\n          class {\n            name\n            slug\n          }\n        }\n        raidProgression {\n          raid\n          total_bosses\n          heroic_bosses_killed\n          mythic_bosses_killed\n          normal_bosses_killed\n          expansion_id\n        }\n        currentSeason {\n          all { score color }\n          dps { score color }\n          healer { score color }\n          tank { score color }\n        }\n        previousSeason {\n          all { score color }\n          dps { score color }\n          healer { score color }\n          tank { score color }\n        }\n      }\n    }\n  }\n"): typeof import('./graphql').CharacterRaiderIoDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query CharacterSearch($searchString: String!, $region: String!) {\n    characterSuggestions(searchString: $searchString, region: $region) {\n      name\n      realm\n      region\n    }\n  }\n"): typeof import('./graphql').CharacterSearchDocument;


export function graphql(source: string) {
  return (documents as any)[source] ?? {};
}
