/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MythicPlusRouteImport } from './routes/mythic-plus'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as RosterIndexRouteImport } from './routes/roster.index'
import { Route as RegionRealmNameRouteImport } from './routes/$region.$realm.$name'
import { Route as RosterRegionSlugRouteImport } from './routes/roster.$region.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MythicPlusRoute = MythicPlusRouteImport.update({
  id: '/mythic-plus',
  path: '/mythic-plus',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const RosterIndexRoute = RosterIndexRouteImport.update({
  id: '/roster/',
  path: '/roster/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegionRealmNameRoute = RegionRealmNameRouteImport.update({
  id: '/$region/$realm/$name',
  path: '/$region/$realm/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const RosterRegionSlugRoute = RosterRegionSlugRouteImport.update({
  id: '/roster/$region/$slug',
  path: '/roster/$region/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mythic-plus': typeof MythicPlusRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/stats': typeof StatsRoute
  '/roster/': typeof RosterIndexRoute
  '/$region/$realm/$name': typeof RegionRealmNameRoute
  '/roster/$region/$slug': typeof RosterRegionSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mythic-plus': typeof MythicPlusRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/stats': typeof StatsRoute
  '/roster': typeof RosterIndexRoute
  '/$region/$realm/$name': typeof RegionRealmNameRoute
  '/roster/$region/$slug': typeof RosterRegionSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mythic-plus': typeof MythicPlusRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/stats': typeof StatsRoute
  '/roster/': typeof RosterIndexRoute
  '/$region/$realm/$name': typeof RegionRealmNameRoute
  '/roster/$region/$slug': typeof RosterRegionSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/mythic-plus'
    | '/privacy-policy'
    | '/stats'
    | '/roster/'
    | '/$region/$realm/$name'
    | '/roster/$region/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mythic-plus'
    | '/privacy-policy'
    | '/stats'
    | '/roster'
    | '/$region/$realm/$name'
    | '/roster/$region/$slug'
  id:
    | '__root__'
    | '/'
    | '/mythic-plus'
    | '/privacy-policy'
    | '/stats'
    | '/roster/'
    | '/$region/$realm/$name'
    | '/roster/$region/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MythicPlusRoute: typeof MythicPlusRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  StatsRoute: typeof StatsRoute
  RosterIndexRoute: typeof RosterIndexRoute
  RegionRealmNameRoute: typeof RegionRealmNameRoute
  RosterRegionSlugRoute: typeof RosterRegionSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mythic-plus': {
      id: '/mythic-plus'
      path: '/mythic-plus'
      fullPath: '/mythic-plus'
      preLoaderRoute: typeof MythicPlusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roster/': {
      id: '/roster/'
      path: '/roster'
      fullPath: '/roster/'
      preLoaderRoute: typeof RosterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$region/$realm/$name': {
      id: '/$region/$realm/$name'
      path: '/$region/$realm/$name'
      fullPath: '/$region/$realm/$name'
      preLoaderRoute: typeof RegionRealmNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roster/$region/$slug': {
      id: '/roster/$region/$slug'
      path: '/roster/$region/$slug'
      fullPath: '/roster/$region/$slug'
      preLoaderRoute: typeof RosterRegionSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MythicPlusRoute: MythicPlusRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  StatsRoute: StatsRoute,
  RosterIndexRoute: RosterIndexRoute,
  RegionRealmNameRoute: RegionRealmNameRoute,
  RosterRegionSlugRoute: RosterRegionSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
